### ISSUE TITLE
ungrammatical

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/posextract#102]
**The AMA purportedly released a statement saying that they had no involvement with the Hollister riot, and, the trouble was caused by the one per cent deviant that tarnishes the public image of both motorcycles and motorcyclists and that the other ninety-nine per cent of motorcyclists are good, decent, law-abiding citizens.**

AMA released purportedly
AMA released statement
they had no involvement
AMA caused by deviant (get rid of)
trouble caused by deviant
that tarnishes image

**Those that remained were quickly subjugated, and the Dark Current settled into the worlds oceans, cutting off each land from its neighbors and turning the sky black.**

Those subjugated quickly
Dark Current settled into oceans
Those settled into oceans (get rid of)
Dark Current cutting land
Dark Current cutting from neighbors

**Coleman and the other members of his 1950s quartet, trumpeter Don Cherry, bassist Charlie Haden, and drummer Billy Higgins, performed on one of the two records, while his electrified ensemble, Prime Time, performed on the other.**

Coleman performed on one
Coleman performed on other (get rid of)
ensemble performed on other
members performed on one
members performed on other (get rid of)

**Comment by alexanderr** [comment]
Example 1:
```
(verb=caused) considering parent: released with POS= VERB
dependency of released->caused: conj
```

Example 2:
```
(verb=settled) considering parent: subjugated with POS= VERB
dependency of subjugated->settled: conj
```

**Comment by stephbuon** [comment]
Latest logic fixed.
