### ISSUE TITLE
Negation 

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/posextract#81]
Question 1:

How do we extract negation? With just "neg" as dependency? 

"no", "not", "never"

Question 2:

**He meant no disrespect by that expression; but he would like to ask whether the ruling was intended to imply that those portions of the Address, prior in point of verbal order to a subject that had been discussed, were not open to any debate, although they had not been even referred to in such discussion?**

We should extract "he-meant-no-disrespect" but we extract "he-meant-disrespect"

Question 3: 

**"Having seized upon a district, they did not attempt to establish themselves permanently or to organize any form of Government; but after a while moved on to some other place, leaving that which they had occupied utterly desolate."**

We extract: "they establish themselves" but should have "they not establish themselves."

**Comment by alexanderr** [comment]
Current extractions: ```they not seize upon district
they not establish themselves
they not establish permanently
they not moved after while
they not moved to place
they occupied which
they occupied utterly desolate```

**Comment by stephbuon** [comment]
@alexanderr did you push these updates? 

I just updated posextract but still get these extractions: 

```
they seize upon district
they establish themselves
they establish permanently
they moved after while
they moved to place
they occupied which
they occupied utterly desolate
```
